config/routes.php
<?php
use Cake\Core\Plugin;
use Cake\Routing\Router;

const DEFAULT_HOMEROUTE = ['controller' => 'Users', 'action' => 'dashboard', 'prefix' => true, 'plugin' => false];
const PREFIXES = [
	'admin' => ['role' => 'A'],
	'founder' => ['role' => 'F'],
	'operating_board' => ['role' => 'O'],
	'user' => ['role' => 'C'],
	'copywriter' => ['role' => 'W'],
	'organizing_committee' => ['role' => 'R'],
	'_' => ['role' => false] //Fake prefix to redirect automatically to the right user prefix (for the CKEditor links)
];

Router::defaultRouteClass('InflectedRoute');

Router::scope('/', function ($routes) {
  $routes->extensions(['json']);
  
  $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);
  $routes->connect('/register', ['controller' => 'Users', 'action' => 'register']);
  $routes->connect('/login', ['controller' => 'Users', 'action' => 'login']);
  $routes->connect('/logout', ['controller' => 'Users', 'action' => 'logout']);
  $routes->connect('/forgot-password', ['controller' => 'Users', 'action' => 'forgot_password_step_1']);
  $routes->connect('/reset-password/*', ['controller' => 'Users', 'action' => 'forgot_password_step_2']);
  $routes->connect('/terms-and-conditions', ['controller' => 'Pages', 'action' => 'terms_and_conditions']);

  $routes->connect('/chat_refresh', ['controller' => 'Chat', 'action' => 'chat_refresh']);

  // $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

  $routes->fallbacks();
});


foreach (PREFIXES as $prefix => $options) {
	
	Router::prefix($prefix, function($routes) use ($prefix, $options) {
		$routes->extensions(['json']);
		
		$homeRoute = (! empty($options['home_route'])) ? $options['home_route'] : DEFAULT_HOMEROUTE;
		
		if (! empty($homeRoute['prefix']) && $homeRoute['prefix'] === true) {
			$homeRoute['prefix'] = $prefix;
		}
		
		$routes->connect('/', $homeRoute);
		
		$routes->connect('/events', ['controller' => 'Events', 'action' => 'index']);
		
		$routes->connect('/forum', ['controller' => 'ForumPosts']);
		$routes->connect('/forum/:action/*', ['controller' => 'ForumPosts']);

		// $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
		$routes->fallbacks();
	});
	
}

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Group.php
<?php
namespace App\Model\Entity;

use Cake\Collection\Collection;
use Cake\Core\Configure;
use Cake\ORM\Query;
use Cake\ORM\TableRegistry;
use Cake\Routing\Router;

class Group extends Entity {

	use VoteDecisionTrait;
	
	private function _findProfileImg($width, $image) {
		$profileImg = Router::url('/img/'.$image.'.jpg', true);
		
		if (!empty($this->profile_img))
			$profileImg = $this->profile_img->url(['width' => $width]);
		
		return $profileImg;
	}
	
	protected function _getProfileTiny() {
		return $this->_findProfileImg('50', 'group-profile-tiny');
	}
	
	protected function _getProfileThumb() {
		return $this->_findProfileImg('120', 'group-profile-thumb');
	}
	
	protected function _getProfileImgUrl() {
		return $this->_findProfileImg('200', 'group-profile-img');
	}
	
	protected function _getBannerImgUrl() {
		$bannerImg = Router::url('/img/banner-img.jpg', true);
		
		if (!empty($this->banner_img))
			$bannerImg = $this->banner_img->url(['height' => '200']);
		
		return $bannerImg;
	}
	
	
	protected function _getSingleLineAddress() {
		
		$a = [];
		
		if (!empty($this->address))
			$a[] = h($this->address);
		
		if (!empty($this->address2))
			$a[] = h($this->address2);
		
		if (!empty($this->city))
			$a[] = h($this->city);
		
		$b = [];
		
		if (!empty($this->region))
			$b[] = $this->region;
		
		if (!empty($this->postal_code))
			$b[] = h($this->postal_code);
		
		if (!empty($this->country))
			$b[] = $this->country;
		
		$a[] = implode(' ', $b);
		
		return implode(', ', $a);
	}
	
	protected function _getMultiLineAddress() {
		$a = [];
		
		if (!empty($this->address))
			$a[] = h($this->address);
		
		if (!empty($this->address2))
			$a[] = h($this->address2);
		
		if (!empty($this->city) || !empty($this->region) || !empty($this->postal_code)) {
			$city = [];
			$region = [];
			
			if (!empty($this->city))
				$city[] = h($this->city);
			
			if (!empty($this->region))
				$region[] = $this->region;
			
			if (!empty($this->postal_code))
				$region[] = h($this->postal_code);
			
			if (!empty($region))
				$city[] = implode(' ', $region);
			
			if (!empty($city))
				$a[] = implode(', ', $city);
		}
		
		if (!empty($this->country))
			$a[] = $this->country;
		
		
		return implode('<br />', $a);
	}
	
	public function getRelatedGroups(User $authUser = null) {

		if (empty($id = $this->id))
			return false;

		if (!empty($authUser))
			$authUserGroupIds = $authUser->getGroupIds();

		if (empty($authUserGroupIds))
			$authUserGroupIds = [0];

		$Groups = TableRegistry::get('Groups');

		$groupIds = $Groups->findById($id)
			->contain([
				'Users.Groups' => function ($query) use ($id, $authUserGroupIds) {

					return $query
						->where([
							'OR' => [
								[
									'Groups.id !=' => $id,
									'Groups.hidden' => false
								],
								[
									'Groups.id !=' => $id,
									'Groups.id IN' => $authUserGroupIds
								]
							]
						]);

				}
			])
			->extract('users.{*}.groups.{*}.id')
			->toArray();

		if (empty($groupIds))
			return false;

		return $Groups->find()
			->contain([
				'ProfileImg'
			])
			->where([
				'Groups.id IN' => array_unique($groupIds)
			]);

	}
	
	public function getMemberCount() {
		
		if (empty($this->id))
			return false;
		
		$Users = TableRegistry::get('Users');
		
		return $Users->find()
			->matching('Groups', function(Query $q) {
				return $q->where(['Groups.id' => $this->id]);
			})
		->count();
	}

	public function getRelatedGroupsProjects() {

		if (empty($this->getRelatedGroups())) {
			return;
		}

		return (new Collection($this->getRelatedGroups()
		->contain([
			// 'Events.Users',
			'Projects' => [
				'Users',
				'Groups'
				// 'Events.Projects.Users'
			],
		])))
		->extract('projects')
		->unfold()
		->toArray();

	}



	public function canDelete() {
		return ($this->getMemberCount() == 0);
	}

	public function hasPermission(User $authUser) {

		if (!in_array($authUser->role, ['A']) && $this->hidden && !in_array($this->id, $this->getGroupIds()))
			return false;

		return true;

	}

	public function isAdmin(User $user) {

		$GroupsUsers = TableRegistry::get('GroupsUsers');

		$groupsUsers = $GroupsUsers->findByGroupIdAndUserId($this->id, $user->id)
			->first();

		if (empty($groupsUsers))
			return false;

		return $groupsUsers->admin;

	}

  public function getGroupAdmins($groupId) {

    $GroupsUsers = TableRegistry::get('GroupsUsers');

    $Users = TableRegistry::get('Users');

    $adminGroups = $GroupsUsers->findByGroupId($groupId)
      ->where(['admin' => 1]);

		if(! empty($adminGroups) )	{
			$admins = [];
			foreach ($adminGroups as $adminGroup) {
				if($admin = $Users->findById($adminGroup->user_id)->first())
					$admins[] = $admin;
			}

			return $admins;
		}

		return false;
  }

	public function getRequestStatus(User $user) {

		$Groups = TableRegistry::get('Groups');

		$group = $Groups->get($this->id, [
			'contain' => [
				'Users' => [
					'conditions' => [
						'Users.id' => $user->id
					]
				]
			]
		]);

		if (!empty($group->users))
			return '';

		if (empty($this->group_requests)) {

			$group = $Groups->get($this->id, [
				'contain' => [
					'GroupRequests'
				]
			]);

			$groupRequests = $group->group_requests;

		} else
			$groupRequests = $this->group_requests;

		$indexedGroupRequests = (new Collection($groupRequests))->indexBy('user_id')->toArray();

		if (array_key_exists($user->id, $indexedGroupRequests))
			return $indexedGroupRequests[$user->id]->status;

		return '';

	}

}

src/Model/Table/GroupsTable.php
<?php
namespace App\Model\Table;

use Cake\Validation\Validator;

class GroupsTable extends Table {

	protected $_activeStatuses = ['A'];

	protected $_order = ['name'];

	public $statuses = [
		'A' => 'Active',
		'D' => 'Deleted'
	];

	public function initialize(array $config) {
		parent::initialize($config);

		$this->addAssociations([
			'hasMany' => [
				'GroupRequests',
				'Events' => [
					'conditions' =>[
						'project_id' => 0
					],
					'sort' => [
						'Events.start_date' => 'DESC'
					]
				],
				'ForumPostWhitelists' => [
					'foreignKey' => 'model_id',
					'conditions' => [
						'ForumPostWhitelists.model' => 'GroupsTable'
					]
				]
			],
			'belongsTo' => [
				'Categories' => [
					'conditions' => [
						'Categories.model' => 'Groups'
					]
				]
			],
			'belongsToMany' => [
				'Users' => [
					'joinTable' => 'groups_users'
				],
				'ForumPosts' => [
					'joinTable' => 'forum_posts_groups',
				],
				'Tags' => [
					'joinTable' => 'groups_tags'
				],
				'Projects' => [
					'joinTable' => 'projects_groups'
				],
				'Initiatives' => [
					'joinTable' => 'initiatives_groups'
				],
			]
		]);

		$this->addBehavior('AssetManager.Asset', [
			'hasOne' => [
				'ProfileImg' => [
					'type' => 'image',
					'ratio' => 1
				],
				'BannerImg' => [
					'type' => 'image'
				]
			]
		]);

	}

	public function getGroup($id) {

		return $this->findById($id)
			->contain([
				'Events.Users',
				'Projects' => [
					'Users',
					'Events.Projects.Users'
				],
				'ForumPosts' => function ($q) {

					return $q->contain('Users')
						->where(['ForumPosts.parent_id IS' => null]);

				},
				'ProfileImg',
				'BannerImg',
				'Categories',
				'Users' => [
					'ProfileImg',
					'conditions' => [
						'Users.pending' => false
					]
				],
				'Tags',
				'GroupRequests' => [
					'Users.ProfileImg',
					'conditions' => [
						'GroupRequests.status' => 'P'
					]
				]
			])
			->first();
	}

	public function getProjects($id) {

		return $this->Projects->findByGroupId($id)
			->toArray();
	}

	public function validationDefault(Validator $validator) {
		return $validator
			->notEmpty('address', 'Address is required')
			->allowEmpty('description')
			->add('description', [
				'max250' => [
					'rule' => ['maxLength', 250],
					'message' => 'The character limit is 250',
				]
			]);
	}

	public function buildUserRoleConditions(\App\Model\Entity\User $authUser, $modelName = 'Groups') {

		$groupIds = $authUser->getGroupIds();

		if (empty($groupIds))
			$groupIds = [0];

		$conditions = [];

		if (!in_array($authUser->role, ['A'])) {

			$conditions['OR'][$modelName.'.hidden'] = false;
			$conditions['OR'][$modelName.'.id IN'] = $groupIds;

		}

		if (!in_array($authUser->role, ['A', 'O'])) {

			if (!empty($conditions['OR'])) {

				$conditions[]['OR'] = $conditions['OR'];

				unset($conditions['OR']);

				$conditions[]['OR'] = [
					$modelName.'.pending' => false,
					$modelName.'.id IN' => $groupIds
				];

			} else {

				$conditions['OR'][$modelName.'.pending'] = false;
				$conditions['OR'][$modelName.'.id IN'] = $groupIds;

			}

		}

		return $conditions;

	}

	public function categorize(array $groups) {

		$categories = $this->Categories->findByModel('Groups')
			->combine('id', 'name')
			->toArray();

		$return = [];

		foreach ($groups as $group) {

			$categoryName = $categories[$group->category_id];

			if (!isset($return[$categoryName]))
				$return[$categoryName] = [];

			$return[$categoryName][] = $group;

		}

		return $return;

	}

}

src/Controller/Admin/GroupsController.php
<?php
namespace App\Controller\Admin;

class GroupsController extends \App\Controller\GroupsController {
	
	public function index() {
		$this->_index();
	}
	
	public function view($id) {
		$this->_view($id);
	}
	
	public function add() {
		$this->_add();
	}
	
	public function edit($id) {
		$this->_edit($id);
	}
	
	public function upload_image($id, $imageType) {
		$this->_upload_image($id, $imageType);
	}
	
	public function ajax_delete_image() {

		$this->_ajax_delete_image();

	}

	public function ajax_reset_image() {

		$this->_ajax_reset_image();

	}
	public function delete($id) {
		$this->_delete($id);
	}

	public function ajax_html_member_list() {

		$this->_ajax_html_member_list();

	}

	public function ajax_add_member() {

		$this->_ajax_add_member();

	}

	public function ajax_group_access() {

		$this->_ajax_group_access();

	}

	public function ajax_group_admin() {

		$this->_ajax_group_admin();

	}

	public function ajax_user_alias() {

		$this->_ajax_user_alias();

	}

  public function ajax_leave_group() {

		$this->_ajax_leave_group();

	}

}

src/Controller/Founder/GroupsController.php
<?php
namespace App\Controller\Founder;

class GroupsController extends \App\Controller\GroupsController {
	
	public function index() {
		$this->_index();
	}
	
	public function view($id) {
		$this->_view($id);
	}
	
	public function add() {
		$this->_add();
	}
	
	public function edit($id) {
		$this->_edit($id);
	}
	
	public function upload_image($id, $imageType) {
		$this->_upload_image($id, $imageType);
	}
	
	public function ajax_reset_image() {

		$this->_ajax_reset_image();

	}

	public function ajax_delete_image() {

		$this->_ajax_delete_image();

	}

	public function delete($id) {
		$this->_delete($id);
	}

	public function ajax_html_member_list() {

		$this->_ajax_html_member_list();

	}

	public function ajax_add_member() {

		$this->_ajax_add_member();

	}

	public function ajax_group_access() {

		$this->_ajax_group_access();

	}

	public function ajax_group_admin() {

		$this->_ajax_group_admin();

	}


  public function ajax_leave_group() {

		$this->_ajax_leave_group();

	}

}

src/Controller/OperatingBoard/GroupsController.php
<?php

namespace App\Controller\OperatingBoard;

class GroupsController extends \App\Controller\GroupsController {

	public function index() {

		$this->_index();

	}

	public function view($id) {

		$this->_view($id);

	}

	public function add() {

		$this->_add();

	}

	public function upload_image($id, $imageType) {

		$this->_upload_image($id, $imageType);

	}

	public function ajax_reset_image() {

		$this->_ajax_reset_image();

	}

	public function ajax_delete_image() {

		$this->_ajax_delete_image();

	}

	public function ajax_html_member_list() {

		$this->_ajax_html_member_list();

	}

	public function ajax_add_member() {

		$this->_ajax_add_member();

	}

	public function ajax_group_access() {

		$this->_ajax_group_access();

	}

	public function ajax_group_admin() {

		$this->_ajax_group_admin();

	}

  public function ajax_leave_group() {

		$this->_ajax_leave_group();

	}

}

src/Controller/OrganizingCommittee/GroupsController.php
<?php

namespace App\Controller\OrganizingCommittee;

class GroupsController extends \App\Controller\GroupsController {

	public function index() {

		$this->_index();

	}

	public function view($id) {

		$this->_view($id);

	}

	public function add() {

		$this->_add();

	}

	public function edit($id) {

		$this->_edit($id);

	}

	public function upload_image($id, $imageType) {

		$this->_upload_image($id, $imageType);

	}

	public function ajax_reset_image() {

		$this->_ajax_reset_image();

	}

	public function ajax_delete_image() {

		$this->_ajax_delete_image();

	}

	public function ajax_html_member_list() {

		$this->_ajax_html_member_list();

	}

	public function ajax_add_member() {

		$this->_ajax_add_member();

	}

	public function ajax_group_access() {

		$this->_ajax_group_access();

	}

	public function ajax_group_admin() {

		$this->_ajax_group_admin();

	}

  public function ajax_leave_group() {

		$this->_ajax_leave_group();

	}

}

src/Controller/User/GroupsController.php
<?php

namespace App\Controller\User;

class GroupsController extends \App\Controller\GroupsController {

	public function index() {

		$this->_index();

	}

	public function view($id) {

		$this->_view($id);

	}

	public function add() {

		$this->_add();

	}

	public function edit($id) {

		$this->_edit($id);

	}

	public function upload_image($id, $imageType) {

		$this->_upload_image($id, $imageType);

	}

	public function ajax_reset_image() {

		$this->_ajax_reset_image();

	}

	public function ajax_delete_image() {

		$this->_ajax_delete_image();

	}

	public function ajax_html_member_list() {

		$this->_ajax_html_member_list();

	}

	public function ajax_add_member() {

		$this->_ajax_add_member();

	}

	public function ajax_group_access() {

		$this->_ajax_group_access();

	}

	public function ajax_group_admin() {

		$this->_ajax_group_admin();

	}

  public function ajax_leave_group() {

		$this->_ajax_leave_group();

	}

}

src/Template/Groups/_ajax_html_member_list.ctp
<?php if (!empty($group->users)): ?>

	<ul class="list-group user-list-group">

		<?php foreach ($group->users as $user): ?>

			<li class="list-group-item">
				<?= $this->Html->link(
					sprintf(
						'%s %s',
						$this->Html->image($user->profile_thumb, ['class' => 'img-circle']),
						$user->name
					),
					['controller' => 'Users', 'action' => 'view', $user->id],
					['escape' => false]
				); ?>

				<div class="pull-right checkbox-group-admin">

					<?= $this->Form->input('admin_'.$user->id, [
						'type' => 'checkbox',
						'label' => 'Admin',
						'default' => $user->_joinData->admin,
						'data-id' => $user->_joinData->id,
						'onclick' => 'groupAdmin(this)'
					]); ?>

				</div>

			</li>

		<?php endforeach; ?>

	</ul>

<?php endif; ?>

src/Template/Groups/_form.ctp
<?php

$this->Html->css('plugins/chosen/chosen.min', ['block' => true]);

$this->Html->script('plugins/chosen/chosen.jquery.min', ['block' => true]);

?>

<?= $this->element('ckeditor') ?>

<?= $this->Html->scriptBlock(
	<<<JS

	var memberList = function () {

		$.post(
			'{$this->Url->build(['action' => 'ajax_html_member_list'])}',
			{
				id: '{$group->id}'
			},
			function (response) {

				$('#member-list').html(response);

			}
		);

	};

	var addUser = function (self) {

		$.post(
			'{$this->Url->build(['action' => 'ajax_add_member'])}.json',
			{
				id: '{$group->id}',
				user_id: $(self).data('id')
			},
			function () {

				$(self).hide();

				memberList();

			}
		);

	};

	var groupAccess = function (self) {

		$.post(
			'{$this->Url->build(['action' => 'ajax_group_access'])}.json',
			{
				group_request_id: $(self).data('id'),
				type: $(self).data('type')
			},
			function (response) {

				if (response.status == 'ok')
					$('#group-access-buttons-' + $(self).data('id')).hide();

			}
		);

	};

	var groupAdmin = function (self) {

		$.post(
			'{$this->Url->build(['action' => 'ajax_group_admin'])}.json',
			{
				groups_users_id: $(self).data('id'),
				admin: $(self).prop('checked') | 0
			}
		);

	};
	
	var userAlias = function (self) {

		$.post(
			'{$this->Url->build(['action' => 'ajax_user_alias'])}.json',
			{
				groups_users_id: $(self).data('id'),
				alias: $(self).val()
			}
		);

	};

	$(function() {

		$('#category-id').change(function () {

			var _checkboxHidden = $('#checkbox-hidden');

			if ($(this).val() == 3)
				_checkboxHidden.hide();
			else
				_checkboxHidden.show();

		});

		$('#tags-ids').chosen({

			placeholder_text_multiple: 'Enter Tags',
      create_option: true,
			single_backstroke_delete:	true

		});



		var addMemberTimeout;

		$('#add-member').keypress(function () {

			window.clearTimeout(addMemberTimeout);

			var self = this;

			addMemberTimeout = window.setTimeout(function () {

				$.post(
					'{$this->Url->build(['controller' => 'Users', 'action' => 'ajax_html_user_list'])}',
					{
						id: '{$group->id}',
						term: $(self).val(),
						model: 'Groups'
					},
					function (response) {

						$('#add-member-response').html(response);

					}
				);

			}, 500);

		});

		memberList();

	});

JS
	, ['block' => true]); ?>

<?= $this->Form->create($group); ?>

<?php if (!empty($group->id)): ?>

	<div class="profile-banner" style="background-image: url(<?= $group->banner_img_url ?>">

		<div class="profile-img-wrapper">
			<?= $this->Html->image($group->profile_img_url.'?'.microtime(true)); ?>
			<?= $this->Html->link(
				'Change Profile Image',
				['action' => 'upload_image', $group->id, 'profile_img'],
				['escape' => false, 'class' => 'btn btn-info']
			); ?>
		</div>

		<?= $this->Html->link(
			'Change Banner Image',
			['action' => 'upload_image', $group->id, 'banner_img'],
			['escape' => false, 'class' => 'btn btn-info pull-right']
		); ?>

		<h1><?= $group->name ?></h1>
		<?= (!empty($group->description)) ? '<p>' . $group->description . '</p>' : '' ?>

	</div>

<?php endif; ?>

<div class="row">
	<div class="col-sm-16">


		<div class="ibox">
			<div class="ibox-title">
				<span><?= $icons['edit'] ?></span>
				<h3>Main Information</h3>
			</div>
			<div class="ibox-content" style="overflow: visible;">

				<div class="row">

					<div class="col-md-9">
						<?= $this->Form->input('category_id'); ?>
					</div>

					<div class="col-md-3" id="checkbox-hidden"<?= $group->category_id == 3 ? ' style="display: none;"' : ''; ?>>
						<label>&nbsp;</label>
						<?= $this->Form->input('hidden', ['label' => 'Visible to Group Only']); ?>
					</div>

					<?php if (in_array($authUser->role, ['A'])): ?>

						<div class="col-md-4">
							<?= $this->Form->label('pending', 'Status'); ?>
							<?= $this->Form->input('pending'); ?>
						</div>

						<div class="col-md-4">
							<label>&nbsp;</label>
							<?= $this->Form->input('donations', [
								'label' => 'Accept Donations'
							]); ?>
						</div>
						<div class="col-md-4">
							<label>&nbsp;</label>
							<?= $this->Form->input('passive'); ?>
						</div>

					<?php endif; ?>

				</div>

				<?= $this->Form->input('name') ?>

				<?= $this->Form->input('description', [
					'type' => 'textarea',
					'rows' => 3,
					'help' => 'Maximum 250 characters'
				]) ?>
				<label>Main Email<span style="color:red">*</span></label>
				<?= $this->Form->input('email', ['label' => false, 'required']) ?>
				<label>Phone Number<span style="color:red">*</span></label>
				<?= $this->Form->input('phone', ['label' => false, 'required']) ?>
				<?= $this->Form->input('website', ['prepend' => 'http://']) ?>
				<?= $this->Form->input('tags._ids'); ?>

			</div>
		</div>

	</div>

	<div class="col-sm-8">

		<div class="ibox">
			<div class="ibox-title">
				<span><?= $icons['users'] ?></span>
				<h3>Members</h3>
			</div>
			<div class="ibox-content" style="max-height: 300px; overflow-y: scroll;">

				<?php if ($group->isNew()): ?>

					<div class="alert alert-info">
						You will be able to add members after saving the group.
					</div>

				<?php else: ?>

					<?php if (in_array($authUser->role, ['A', 'O']) || $group->isAdmin($authUser)): ?>

						<?= $this->Form->input(
							'add_member',
							[
								'placeholder' => 'Search for Contact Name'
							]
						); ?>

						<div id="add-member-response"></div>

					<?php endif; ?>

					<div id="member-list"></div>

				<?php endif; ?>

			</div>
		</div>

		<?php if (in_array($authUser->role, ['A']) || $group->isAdmin($authUser)): ?>

			<div class="ibox">
				<div class="ibox-title">
					<span><?= $icons['user-plus']; ?></span>
					<h3>Pending Access Requests</h3>
				</div>

				<div class="ibox-content" style="max-height: 300px; overflow-y: scroll;">

					<ul class="list-group user-list-group">

						<?php if (!empty($group->group_requests)): ?>

							<?php foreach ($group->group_requests as $request): ?>

								<li class="list-group-item">
									<?= $this->Html->link(
										sprintf(
											'%s %s',
											$this->Html->image($request->user->profile_thumb, ['class' => 'img-circle']),
											$request->user->name
										),
										['controller' => 'Users', 'action' => 'view', $request->user->id],
										['escape' => false]
									); ?>

									<div id="group-access-buttons-<?= $request->id; ?>" class="pull-right">

										<?= $this->Html->link(
											'Accept',
											'javascript:;',
											[
												'class' => 'btn btn-sm btn-primary',
												'onclick' => 'groupAccess(this)',
												'data-id' => $request->id,
												'data-type' => 'A'
											]
										); ?>

										<?= $this->Html->link(
											'Reject',
											'javascript:;',
											[
												'class' => 'btn btn-sm btn-danger',
												'onclick' => 'groupAccess(this)',
												'data-id' => $request->id,
												'data-type' => 'R'
											]
										); ?>

									</div>
								</li>

							<?php endforeach; ?>

						<?php else: ?>

							<li class="list-group-item disabled">
								No requests found.
							</li>

						<?php endif; ?>

					</ul>

				</div>
			</div>

		<?php endif; ?>

	</div>

</div>

<div class="row">
	<div class="col-md-12">

		<div class="ibox">
			<div class="ibox-title">
				<span><?= $icons['map-marker'] ?></span>
				<h3>Address</h3>
			</div>
			<div class="ibox-content">

				<?= $this->Form->input('address'); ?>
				<?= $this->Form->input('address2', ['label' => false]); ?>

				<div class="row">
					<div class="col-sm-6">
						<?= $this->Form->input('city'); ?>
					</div>
					<div class="col-sm-6">
						<?= $this->Form->input('postal_code'); ?>
					</div>
					<div class="col-sm-6">
						<?= $this->Form->input('region', ['label' => 'Province/State']); ?>
					</div>
					<div class="col-sm-6">
						<?= $this->Form->input('country'); ?>
					</div>
				</div>

			</div>
		</div>

	</div>
	<div class="col-md-12">

		<div class="ibox">
			<div class="ibox-title">
				<span><?= $icons['align-left'] ?></span>
				<h3>About Us</h3>
			</div>
			<div class="ibox-content">
				<?= $this->Form->input('bio', ['class' => 'ckeditor']); ?>
			</div>
		</div>

	</div>

</div>


<div class="submit-big">
	<?= $this->Form->submit('Save', ['bootstrap-type' => 'primary']); ?>
</div>

<?= $this->Form->end() ?>